### ISSUE TITLE
lannister

### ISSUE THREAD

**Issue by gsaibabu** [elastic-project/genesis-block#1]

**Comment by gsaibabu** [comment]
Hi Lannnister,

i sent 0.05 BTC to the adress(3Qnj4QtdD4qtZcP82xyLq2paAEPDgfwezd) to cowdfund your elastic project .And its block is 401570. and its BTC transaction no is: 9712be14e37f28307874d8507d68e648ddd776c1f8ed12de779e87119aa9895e.
But ELC are not credited it seems

**Comment by ZionSky** [comment]
You will get credited at the end of the crowd sale.

**Comment by gsaibabu** [comment]
When i am looking at genesis blockrepository on  Github ..I am able to see details of others with block and transaction no.

Bu iam not able to see

**Comment by elastic-project** [comment]
@gsaibabu: I will credit you manually. Sorry for the inconvenience, sometimes transactions get lost if they come from a multisig wallet. I will check.

**Comment by gsaibabu** [comment]
Thanks for reply. It seems i can see that block on repositry soon...

**Comment by gsaibabu** [comment]
whether i can get elastic coins or i will get credited my bitcoins...

**Comment by gsaibabu** [comment]
Hi Lannnister,

i sent 0.05 BTC to the adress(3Qnj4QtdD4qtZcP82xyLq2paAEPDgfwezd) to cowdfund your elastic project .And its block is 401570. and its BTC transaction no is: 9712be14e37f28307874d8507d68e648ddd776c1f8ed12de779e87119aa9895e.
But ELC are not credited it seems
